# Physical GPIO buttons on the Waveshare board.

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    name: "Volume Down"
    filters:
      - delayed_on: 20ms
    on_press:
      - lambda: |-
          float v = id(speaker_volume) - 0.1f;
          if (v < 0.1f) v = 0.1f;
          id(speaker_volume) = v;
          id(es8311_codec).set_volume(v);
          id(number_volume).publish_state(v * 100.0f);
  - platform: gpio
    pin:
      pca9554: expander
      number: 4
      mode:
        input: true
      inverted: true
    name: "Volume Up"
    filters:
      - delayed_on: 20ms
    on_press:
      - lambda: |-
          float v = id(speaker_volume) + 0.1f;
          if (v > 1.0f) v = 1.0f;
          id(speaker_volume) = v;
          id(es8311_codec).set_volume(v);
          id(number_volume).publish_state(v * 100.0f);
