# Physical GPIO buttons on the Waveshare board.

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    name: "Volume Down"
    filters:
      - delayed_on: 20ms
    on_press:
      - lambda: 'id(last_touch_ms) = millis();'
      - script.execute: wake_screen
      - script.execute:
          id: adjust_target_temperature
          delta_tenths: -5
  - platform: gpio
    pin:
      pca9554: expander
      number: 4
      mode:
        input: true
      inverted: true
    name: "Volume Up"
    filters:
      - delayed_on: 20ms
    on_press:
      - lambda: 'id(last_touch_ms) = millis();'
      - script.execute: wake_screen
      - script.execute:
          id: adjust_target_temperature
          delta_tenths: 5
